Repository redbadger/pride-london-app, pull requests merged in 2018-04, with the labels that each got.

#95 Bumps Fastlane minor version
  android/Gemfile.lock
  android/fastlane/Fastfile
  ios/Gemfile.lock
  ios/fastlane/Fastfile
Labels: ready for review

#82 add instructions to get local device working for iOS
  README.md
Labels: ready for review

#106 Switch dates if end date is before start date
  e2e/init.js
  src/data/get-asset-url.js
  src/data/locale.js
  src/data/locale.test.js
  src/integrations/storage.js
  src/integrations/storage.test.js
  src/screens/EventDetailsScreen/component.js
  src/screens/EventsScreen/component.js
  src/screens/FeaturedEventListScreen/component.js
  src/screens/HomeScreen/component.js
  src/selectors/basic-event-filters.js
  src/selectors/events.js
Labels: ready for review, test in progress

#124 Add accessibility tips to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ready for review

#107 UI for Tab bar
  .flowconfig
  android/app/build.gradle
  android/app/src/main/java/com/pridelondonapp/MainApplication.java
  android/settings.gradle
  assets/images/eventsActive.png
  assets/images/eventsActive@2x.png
  assets/images/eventsActive@3x.png
  assets/images/eventsDefault.png
  assets/images/eventsDefault@2x.png
  assets/images/eventsDefault@3x.png
  assets/images/homeActive.png
  assets/images/homeActive@2x.png
  assets/images/homeActive@3x.png
  assets/images/homeDefault.png
  assets/images/homeDefault@2x.png
  assets/images/homeDefault@3x.png
  assets/images/paradeActive.png
  assets/images/paradeActive@2x.png
  assets/images/paradeActive@3x.png
  assets/images/paradeDefault.png
  assets/images/paradeDefault@2x.png
  assets/images/paradeDefault@3x.png
  assets/images/savedActive.png
  assets/images/savedActive@2x.png
  assets/images/savedActive@3x.png
  assets/images/savedDefault.png
  assets/images/savedDefault@2x.png
  assets/images/savedDefault@3x.png
  assets/images/supportUsActive.png
  assets/images/supportUsActive@2x.png
  assets/images/supportUsActive@3x.png
  assets/images/supportUsDefault.png
  assets/images/supportUsDefault@2x.png
  assets/images/supportUsDefault@3x.png
  flow-typed/npm/react-native-linear-gradient_v2.x.x.js
  flow-typed/npm/react-navigation_v1.x.x.js
  ios/PrideLondonApp.xcodeproj/project.pbxproj
  package.json
  src/App.js
  src/components/NavigationTabBar.js
  src/components/NavigationTabBar.test.js
  src/components/Text.js
  src/components/__snapshots__/NavigationTabBar.test.js.snap
  src/components/__snapshots__/Text.test.js.snap
  src/constants/colors.js
  src/constants/routes.js
  src/constants/text.js
  src/data/image-ref.js
  src/screens/EventDetailsScreen/component.js
  src/screens/EventsScreen/component.js
  src/screens/FeaturedEventListScreen/component.js
  src/screens/FeaturedEventListScreen/component.test.js
  src/screens/HomeScreen/component.js
  yarn.lock
Labels: ready for test

#108 Custom date component to match designs
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/DateRangePicker.js
  src/components/DateRangePickerDay.js
  src/components/DateRangePickerDay.test.js
  src/components/DateRangePickerDialog.js
  src/components/Dialog.js
  src/components/__snapshots__/ConnectedDateFilterDialog.test.js.snap
  src/components/__snapshots__/DateRangePicker.test.js.snap
  src/components/__snapshots__/DateRangePickerDay.test.js.snap
  src/components/__snapshots__/DateRangePickerDialog.test.js.snap
  src/components/__snapshots__/Dialog.test.js.snap
  src/constants/colors.js
Labels: ready for review

#130 fix failing tests on master
  src/components/DateRangePicker.test.js
  src/components/__snapshots__/DateRangePicker.test.js.snap
Labels: ready for review

#135 Bug #112 duplicate featured events
  package.json
  src/selectors/events.js
  src/selectors/events.test.js
  yarn.lock
Labels: bug, ready for review, ready for test

#138 Re-using category labels
  src/components/CategoriesPills.js
  src/components/CategoriesPills.test.js
  src/components/CategoryPill.js
  src/components/CategoryPill.test.js
  src/components/__snapshots__/CategoryPill.test.js.snap
  src/screens/EventDetailsScreen/EventOverview.js
  src/screens/EventDetailsScreen/__snapshots__/EventOverview.test.js.snap
Labels: ready for review

#142 Hide Tab bar on nested screens and add missing header
  src/App.js
  src/components/Header.js
  src/components/Header.test.js
  src/components/IconButton.js
  src/components/IconButton.test.js
  src/components/__snapshots__/Header.test.js.snap
  src/components/__snapshots__/IconButton.test.js.snap
  src/constants/text.js
  src/screens/EventDetailsScreen/__snapshots__/Header.test.js.snap
  src/screens/EventDetailsScreen/component.js
  src/screens/FeaturedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/FeaturedEventListScreen/component.js
Labels: qa approved, ready for review

#137 View Individual Event Details - Buy tickets
  src/components/Button.js
  src/components/Button.test.js
  src/components/ButtonPrimary.js
  src/components/ButtonPrimary.test.js
  src/components/Shadow.js
  src/components/Shadow.test.js
  src/components/__snapshots__/Button.test.js.snap
  src/components/__snapshots__/ButtonPrimary.test.js.snap
  src/components/__snapshots__/Shadow.test.js.snap
  src/constants/colors.js
  src/constants/text.js
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
Labels: ready for review

#145 Fix cropped "Support us" text in tab bar
  src/components/NavigationTabBar.js
  src/components/__snapshots__/NavigationTabBar.test.js.snap
Labels: qa approved, ready for review

#143 Event details - event location
  assets/images/location.png
  assets/images/location@2x.png
  assets/images/location@3x.png
  src/data/event.js
  src/screens/EventDetailsScreen/EventOverview.js
  src/screens/EventDetailsScreen/EventOverview.test.js
  src/screens/EventDetailsScreen/__snapshots__/EventOverview.test.js.snap
Labels: ready for review

#144 Event details - event description
  src/components/Text.js
  src/components/__snapshots__/ButtonPrimary.test.js.snap
  src/components/__snapshots__/CategoriesPills.test.js.snap
  src/components/__snapshots__/CategoryPill.test.js.snap
  src/components/__snapshots__/CheckBox.test.js.snap
  src/components/__snapshots__/ConnectedDateFilterDialog.test.js.snap
  src/components/__snapshots__/DateRangePickerDay.test.js.snap
  src/components/__snapshots__/DateRangePickerDialog.test.js.snap
  src/components/__snapshots__/Dialog.test.js.snap
  src/components/__snapshots__/EventCard.test.js.snap
  src/components/__snapshots__/EventTile.test.js.snap
  src/components/__snapshots__/FilterHeaderButton.test.js.snap
  src/components/__snapshots__/FilterHeaderCategories.test.js.snap
  src/components/__snapshots__/Text.test.js.snap
  src/constants/colors.js
  src/constants/text.js
  src/screens/CategoriesFilterScreen/__snapshots__/Header.test.js.snap
  src/screens/CategoriesFilterScreen/__snapshots__/ListItem.test.js.snap
  src/screens/CategoriesFilterScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/EventDescription.js
  src/screens/EventDetailsScreen/EventDescription.test.js
  src/screens/EventDetailsScreen/EventOverview.js
  src/screens/EventDetailsScreen/__snapshots__/CategoryLabel.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/EventDescription.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/EventOverview.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  src/screens/FeaturedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/HomeScreen/__snapshots__/component.test.js.snap
Labels: ready for review

#150 Event Details - contact details & finalizing layout
  assets/images/call.png
  assets/images/call@2x.png
  assets/images/call@3x.png
  assets/images/email.png
  assets/images/email@2x.png
  assets/images/email@3x.png
  package.json
  src/components/Text.js
  src/components/Text.test.js
  src/components/TextLink.js
  src/components/__snapshots__/ConnectedDateFilterDialog.test.js.snap
  src/components/__snapshots__/DateRangePickerDialog.test.js.snap
  src/components/__snapshots__/Text.test.js.snap
  src/constants/text.js
  src/data/formatters.js
  src/data/formatters.test.js
  src/screens/EventDetailsScreen/ContactDetails.js
  src/screens/EventDetailsScreen/ContactDetails.test.js
  src/screens/EventDetailsScreen/EventDescription.js
  src/screens/EventDetailsScreen/EventMap.js
  src/screens/EventDetailsScreen/EventMap.test.js
  src/screens/EventDetailsScreen/EventOverview.js
  src/screens/EventDetailsScreen/EventOverview.test.js
  src/screens/EventDetailsScreen/__snapshots__/ContactDetails.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/EventDescription.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/EventOverview.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  src/screens/EventDetailsScreen/component.test.js
  yarn.lock
Labels: qa approved, ready for review

#158 Remove unused CategoryLabel component
  src/screens/EventDetailsScreen/CategoryLabel.js
  src/screens/EventDetailsScreen/CategoryLabel.test.js
  src/screens/EventDetailsScreen/__snapshots__/CategoryLabel.test.js.snap
Labels: ready for review

#156 adding in numberOfLines prop to text component
  src/components/Text.js
  src/components/__snapshots__/ButtonPrimary.test.js.snap
  src/components/__snapshots__/CategoriesPills.test.js.snap
  src/components/__snapshots__/CategoryPill.test.js.snap
  src/components/__snapshots__/CheckBox.test.js.snap
  src/components/__snapshots__/ConnectedDateFilterDialog.test.js.snap
  src/components/__snapshots__/DateRangePickerDay.test.js.snap
  src/components/__snapshots__/DateRangePickerDialog.test.js.snap
  src/components/__snapshots__/Dialog.test.js.snap
  src/components/__snapshots__/EventCard.test.js.snap
  src/components/__snapshots__/EventTile.test.js.snap
  src/components/__snapshots__/FilterHeaderButton.test.js.snap
  src/components/__snapshots__/FilterHeaderCategories.test.js.snap
  src/components/__snapshots__/Text.test.js.snap
  src/screens/CategoriesFilterScreen/__snapshots__/Header.test.js.snap
  src/screens/CategoriesFilterScreen/__snapshots__/ListItem.test.js.snap
  src/screens/CategoriesFilterScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/EventDescription.js
  src/screens/EventDetailsScreen/__snapshots__/ContactDetails.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/EventDescription.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/EventOverview.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/FeaturedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/HomeScreen/__snapshots__/component.test.js.snap
  src/screens/SupportUsScreen/__snapshots__/SupportUsButton.test.js.snap
  src/screens/SupportUsScreen/__snapshots__/SupportUsSectionHeader.test.js.snap
  src/screens/SupportUsScreen/__snapshots__/index.test.js.snap
Labels: ready for review

#162 Add shouldComponentUpdate to major components to improve performance
  src/components/DateRangePickerDay.js
  src/components/DateRangePickerDay.test.js
  src/components/EventList.js
  src/components/EventList.test.js
  src/components/__snapshots__/EventList.test.js.snap
  src/screens/HomeScreen/component.js
  src/screens/HomeScreen/component.test.js
Labels: ready for review

#164 Date picker accessibility
  src/components/ConnectedDateFilterDialog.js
  src/components/DateRangePickerDay.js
  src/components/DateRangePickerDialog.js
  src/components/DateRangePickerDialog.test.js
  src/components/Dialog.js
  src/components/Dialog.test.js
  src/components/EventList.js
  src/components/EventList.test.js
  src/components/FilterHeader.js
  src/components/FilterHeaderButton.js
  src/components/FilterHeaderButton.test.js
  src/components/FilterHeaderCategories.js
  src/components/MultiSelectDialog.js
  src/components/__snapshots__/ConnectedDateFilterDialog.test.js.snap
  src/components/__snapshots__/ConnectedFilterHeader.test.js.snap
  src/components/__snapshots__/ConnectedTimeFilterDialog.test.js.snap
  src/components/__snapshots__/DateRangePickerDay.test.js.snap
  src/components/__snapshots__/DateRangePickerDialog.test.js.snap
  src/components/__snapshots__/Dialog.test.js.snap
  src/components/__snapshots__/EventList.test.js.snap
  src/components/__snapshots__/FilterHeader.test.js.snap
  src/components/__snapshots__/FilterHeaderButton.test.js.snap
  src/components/__snapshots__/MultiSelectDialog.test.js.snap
  src/constants/text.js
  src/constants/text.test.js
  yarn.lock
Labels: ready for review

#160 Implement design feedback on EventDetails screen
  src/components/Delayed.js
  src/components/Delayed.test.js
  src/components/LayoutColumn.js
  src/components/LayoutColumn.test.js
  src/components/ShadowedScrollView.js
  src/components/Text.js
  src/components/TextLink.js
  src/components/__snapshots__/ButtonPrimary.test.js.snap
  src/components/__snapshots__/CategoriesPills.test.js.snap
  src/components/__snapshots__/CategoryPill.test.js.snap
  src/components/__snapshots__/CheckBox.test.js.snap
  src/components/__snapshots__/ConnectedDateFilterDialog.test.js.snap
  src/components/__snapshots__/DateRangePickerDay.test.js.snap
  src/components/__snapshots__/DateRangePickerDialog.test.js.snap
  src/components/__snapshots__/Delayed.test.js.snap
  src/components/__snapshots__/Dialog.test.js.snap
  src/components/__snapshots__/EventCard.test.js.snap
  src/components/__snapshots__/EventTile.test.js.snap
  src/components/__snapshots__/FilterHeaderButton.test.js.snap
  src/components/__snapshots__/FilterHeaderCategories.test.js.snap
  src/components/__snapshots__/LayoutColumn.test.js.snap
  src/components/__snapshots__/ShadowedScrollView.test.js.snap
  src/components/__snapshots__/Text.test.js.snap
  src/constants/colors.js
  src/constants/text.js
  src/data/event.js
  src/screens/CategoriesFilterScreen/__snapshots__/Header.test.js.snap
  src/screens/CategoriesFilterScreen/__snapshots__/List.test.js.snap
  src/screens/CategoriesFilterScreen/__snapshots__/ListItem.test.js.snap
  src/screens/CategoriesFilterScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/EventContact.js
  src/screens/EventDetailsScreen/EventContact.test.js
  src/screens/EventDetailsScreen/EventDescription.js
  src/screens/EventDetailsScreen/EventMap.js
  src/screens/EventDetailsScreen/EventMap.test.js
  src/screens/EventDetailsScreen/EventOverview.js
  src/screens/EventDetailsScreen/IconItem.js
  src/screens/EventDetailsScreen/SectionDivider.js
  src/screens/EventDetailsScreen/SectionDivider.test.js
  src/screens/EventDetailsScreen/TextLink.js
  src/screens/EventDetailsScreen/TextLink.test.js
  src/screens/EventDetailsScreen/__snapshots__/ContactDetails.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/EventContact.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/EventDescription.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/EventMap.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/EventOverview.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/IconItem.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/SectionDivider.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/TextLink.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  src/screens/EventDetailsScreen/component.test.js
  src/screens/FeaturedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/HomeScreen/__snapshots__/component.test.js.snap
  src/screens/SupportUsScreen/__snapshots__/SupportUsButton.test.js.snap
  src/screens/SupportUsScreen/__snapshots__/SupportUsSectionHeader.test.js.snap
  src/screens/SupportUsScreen/__snapshots__/index.test.js.snap
Labels: ready for review

#174 Upgrades to latest fastlane and enforces this version
  android/Gemfile.lock
  android/fastlane/Fastfile
  ios/Gemfile.lock
  ios/fastlane/Fastfile
Labels: ready for review

#177 Favourite Event - animated button
  android/app/build.gradle
  android/app/src/main/java/com/pridelondonapp/MainApplication.java
  android/settings.gradle
  assets/animations/favourite-detail.json
  assets/animations/favourite-listing.json
  assets/images/heart-white.png
  assets/images/heart-white@2x.png
  assets/images/heart-white@3x.png
  ios/PrideLondonApp.xcodeproj/project.pbxproj
  package.json
  src/screens/EventDetailsScreen/FavouriteButton.js
  src/screens/EventDetailsScreen/FavouriteButton.test.js
  src/screens/EventDetailsScreen/__snapshots__/FavouriteButton.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  yarn.lock
Labels: qa approved

#172 Event details - icon list layout
  src/screens/EventDetailsScreen/EventContact.js
  src/screens/EventDetailsScreen/EventContact.test.js
  src/screens/EventDetailsScreen/EventDescription.js
  src/screens/EventDetailsScreen/EventOverview.js
  src/screens/EventDetailsScreen/IconItem.js
  src/screens/EventDetailsScreen/IconItem.test.js
  src/screens/EventDetailsScreen/IconList.js
  src/screens/EventDetailsScreen/IconList.test.js
  src/screens/EventDetailsScreen/SectionDivider.js
  src/screens/EventDetailsScreen/TextLink.js
  src/screens/EventDetailsScreen/__snapshots__/EventContact.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/EventOverview.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/IconItem.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/IconList.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/SectionDivider.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/TextLink.test.js.snap
Labels: ready for review

#180 Favourite Event - reducer
  assets/animations/save-event-dark.json
  assets/animations/save-event-light.json
  src/actions/saved-events.js
  src/actions/saved-events.test.js
  src/components/EventCard.js
  src/components/EventCard.test.js
  src/components/EventList.js
  src/components/EventList.test.js
  src/components/SaveEventButton.js
  src/components/SaveEventButton.test.js
  src/components/Text.js
  src/components/__snapshots__/EventCard.test.js.snap
  src/components/__snapshots__/EventList.test.js.snap
  src/components/__snapshots__/SaveEventButton.test.js.snap
  src/components/__snapshots__/Text.test.js.snap
  src/constants/colors.js
  src/data/event.js
  src/reducers/__snapshots__/saved-events.test.js.snap
  src/reducers/index.js
  src/reducers/saved-events.js
  src/reducers/saved-events.test.js
  src/screens/EventDetailsScreen/FavouriteButton.js
  src/screens/EventDetailsScreen/FavouriteButton.test.js
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  src/screens/EventDetailsScreen/component.test.js
  src/screens/EventDetailsScreen/index.js
  src/screens/EventsScreen/__snapshots__/component.test.js.snap
  src/screens/EventsScreen/component.js
  src/screens/EventsScreen/component.test.js
  src/screens/EventsScreen/index.js
  src/screens/FeaturedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/FeaturedEventListScreen/component.js
  src/screens/FeaturedEventListScreen/component.test.js
  src/screens/FeaturedEventListScreen/index.js
  src/selectors/event-filters.test.js
Labels: ready for review

#166 Follow latest CircleCI docs for pre running simulator
  .circleci/config.yml
  BrewFile
  android/app/build.gradle
  e2e/firstTest.spec.js
  e2e/init.js
  ios/PrideLondonApp/Info.plist
  ios/PrideLondonAppTests/Info.plist
  package.json
  yarn.lock
Labels: ready for review

#182 Order venue and accessibility tags alphabetically
  src/data/tags.js
Labels: ready for review

#123 133 Display list of performances (event-details page)
  src/components/Collapsible.js
  src/components/Collapsible.test.js
  src/components/Performance.js
  src/components/Performance.test.js
  src/components/PerformanceList.js
  src/components/PerformanceList.test.js
  src/components/TextLink.js
  src/components/TextLink.test.js
  src/components/__snapshots__/Collapsible.test.js.snap
  src/components/__snapshots__/Performance.test.js.snap
  src/components/__snapshots__/PerformanceList.test.js.snap
  src/components/__snapshots__/TextLink.test.js.snap
  src/constants/text.js
  src/data/event.js
  src/integrations/storage.test.js
  src/screens/EventDetailsScreen/EventContact.js
  src/screens/EventDetailsScreen/EventDescription.js
  src/screens/EventDetailsScreen/EventDescription.test.js
  src/screens/EventDetailsScreen/EventOverview.js
  src/screens/EventDetailsScreen/__snapshots__/EventDescription.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  src/screens/EventsScreen/component.test.js
  src/selectors/events.js
  src/selectors/events.test.js
Labels: ready for review

#185 Add .editorconfig
  .editorconfig
Labels: ready for review

#157 Android Beta Play Store
  .circleci/config.yml
  .gitignore
  android/.bundle/config
  android/app/BUCK
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/pridelondonapp/MainActivity.java
  android/app/src/main/java/com/pridelondonapp/MainApplication.java
  android/fastlane/Appfile
  android/fastlane/Fastfile
  android/fastlane/README.md
  ios/.bundle/config
  ios/fastlane/Fastfile
  ios/fastlane/README.md
  package.json
Labels: ready for review
