Repository redbadger/pride-london-app, pull requests merged in 2018-06, with the labels that each got.

#345 Sponsor refactor
  src/data/__snapshots__/field-ref.test.js.snap
  src/data/__snapshots__/sponsor.test.js.snap
  src/data/field-ref.js
  src/data/field-ref.test.js
  src/data/sponsor.js
  src/data/sponsor.test.js
  src/integrations/cms.js
  src/lib/decode.js
  src/lib/decode.test.js
  src/lib/result.js
  src/lib/result.test.js
  src/reducers/__snapshots__/data.test.js.snap
  src/reducers/data.js
  src/reducers/data.test.js
  src/screens/SponsorScreen/SponsorLogoContainer.js
  src/screens/SponsorScreen/SponsorLogoContainer.test.js
  src/screens/SponsorScreen/__snapshots__/component.test.js.snap
  src/screens/SponsorScreen/component.js
  src/screens/SponsorScreen/component.test.js
  src/screens/SponsorScreen/index.js
  src/selectors/event-filters.test.js
  src/selectors/sponsors.js
  src/selectors/sponsors.test.js
Labels: ready for review

#353 Fix use of old function name
  src/screens/EventsScreen/component.js
  src/screens/EventsScreen/component.test.js
  src/screens/SavedEventListScreen/component.js
  src/screens/SavedEventListScreen/component.test.js
Labels: qa approved

#354 Update ESLint plugins
  package.json
  src/components/ButtonWithShapes.js
  src/components/CategoriesPills.js
  src/components/DateRangePicker.js
  src/components/DateRangePickerDay.js
  src/components/DateRangePickerDialog.js
  src/components/__snapshots__/ButtonWithShapes.test.js.snap
  src/screens/DonateScreen/NumberTextField.js
  src/screens/DonateScreen/__snapshots__/NumberTextField.test.js.snap
  src/screens/HomeScreen/__snapshots__/Header.test.js.snap
  src/screens/SupportUsScreen/__snapshots__/index.test.js.snap
  yarn.lock
Labels: ready for review

#343 Latest version of Fastlane
  android/Gemfile.lock
  android/fastlane/Fastfile
  ios/Gemfile.lock
  ios/fastlane/Fastfile
Labels: ready for review

#361 Add types to react redux connect to propagate types correctly
  src/actions/event-filters.js
  src/components/ConnectedFilterHeader.js
  src/components/DateRangePickerDialog.js
  src/components/DateRangePickerDialogConnected.js
  src/components/DateRangePickerDialogConnected.test.js
  src/components/FilterHeader.js
  src/components/FilterHeader.test.js
  src/components/FilterHeaderConnected.js
  src/components/FilterHeaderConnected.test.js
  src/components/__snapshots__/DateRangePickerDialogConnected.test.js.snap
  src/components/__snapshots__/FilterHeaderConnected.test.js.snap
  src/screens/CategoriesFilterScreen/index.js
  src/screens/EventDetailsScreen/component.js
  src/screens/EventDetailsScreen/index.js
  src/screens/EventsScreen/component.js
  src/screens/EventsScreen/component.test.js
  src/screens/EventsScreen/index.js
  src/screens/FeaturedEventListScreen/index.js
  src/screens/FilterScreen/component.js
  src/screens/FilterScreen/index.js
  src/screens/HomeScreen/index.js
  src/screens/SavedEventListScreen/index.js
  src/screens/SponsorScreen/index.js
  src/selectors/events.js
Labels: ready for review

#358 Animate layout changes in EventList
  src/App.js
  src/components/EventList.js
  src/components/EventList.test.js
  src/components/__snapshots__/EventList.test.js.snap
Labels: ready for review, ready for test

#323 Nightly build which runs only once for a commit
  .circleci/config.yml
Labels: ready for review

#360 Compress images
  assets/images/cabaret.jpg
  assets/images/cabaret@2x.jpg
  assets/images/cabaret@3x.jpg
  assets/images/community.jpg
  assets/images/community@2x.jpg
  assets/images/community@3x.jpg
  assets/images/donateHeader.jpg
  assets/images/donateHeader.png
  assets/images/donateHeader@2x.jpg
  assets/images/donateHeader@2x.png
  assets/images/donateHeader@3x.jpg
  assets/images/donateHeader@3x.png
  assets/images/familyArea.jpg
  assets/images/familyArea@2x.jpg
  assets/images/familyArea@3x.jpg
  assets/images/supportUsAsBusiness.jpg
  assets/images/supportUsAsBusiness@2x.jpg
  assets/images/supportUsAsBusiness@3x.jpg
  assets/images/supportUsAsIndividual.jpg
  assets/images/supportUsAsIndividual@2x.jpg
  assets/images/supportUsAsIndividual@3x.jpg
  assets/images/trafalgarSquare.jpg
  assets/images/trafalgarSquare@2x.jpg
  assets/images/trafalgarSquare@3x.jpg
  assets/images/womensStage2018.jpg
  assets/images/womensStage2018@2x.jpg
  assets/images/womensStage2018@3x.jpg
  src/screens/DonateScreen/index.js
Labels: ready for review, ready for test

#365 HeaderBanner refactor
  src/data/__snapshots__/header-banner.test.js.snap
  src/data/header-banner.js
  src/data/header-banner.test.js
  src/data/locale.js
  src/data/locale.test.js
  src/reducers/__snapshots__/data.test.js.snap
  src/reducers/data.js
  src/reducers/data.test.js
  src/screens/HomeScreen/Header.js
  src/screens/HomeScreen/__snapshots__/component.test.js.snap
  src/screens/HomeScreen/__test-data.js
  src/screens/HomeScreen/component.js
  src/selectors/event-filters.test.js
  src/selectors/header-banner.js
  src/selectors/header-banner.test.js
  src/selectors/sponsors.test.js
Labels: ready for review

#363 Handle error during data refresh
  src/actions/data.js
  src/actions/data.test.js
  src/index.js
  src/reducers/__mocks__/react-native-splash-screen.js
  src/reducers/data.js
  src/reducers/data.test.js
  src/reducers/index.js
  src/reducers/splash-screen.js
  src/reducers/splash-screen.test.js
  src/selectors/event-filters.test.js
Labels: ready for review

#367 We Enjoy Typing
  .codeclimate.yml
Labels: ready for review

#366 Empty event list
  assets/images/emptyList.png
  assets/images/emptyList@2x.png
  assets/images/emptyList@3x.png
  src/constants/text.js
  src/screens/EventsScreen/NoEvents.js
  src/screens/EventsScreen/NoEvents.test.js
  src/screens/EventsScreen/__snapshots__/NoEvents.test.js.snap
  src/screens/EventsScreen/__snapshots__/component.test.js.snap
  src/screens/EventsScreen/component.js
  src/screens/EventsScreen/component.test.js
  src/screens/HomeScreen/__snapshots__/component.test.js.snap
  src/screens/HomeScreen/component.js
Labels: ready for review

#368 Fix crash on Android when animating too many items
  src/App.js
  src/components/EventList.js
  src/components/EventList.test.js
  src/index.js
  src/lib/navigation.js
  src/screens/EventsScreen/component.js
  src/screens/EventsScreen/component.test.js
  src/screens/EventsScreen/index.js
  src/screens/HomeScreen/component.js
  src/screens/HomeScreen/component.test.js
  src/screens/HomeScreen/index.js
  src/screens/SavedEventListScreen/component.js
  src/screens/SavedEventListScreen/component.test.js
  src/screens/SavedEventListScreen/index.js
Labels: ready for review

#370 Refactor test data to use testcheck generators
  package.json
  src/data/__snapshots__/field-ref.test.js.snap
  src/data/__snapshots__/header-banner.test.js.snap
  src/data/__snapshots__/sponsor.test.js.snap
  src/data/__test-data.js
  src/data/event.js
  src/data/field-ref.test.js
  src/data/header-banner.test.js
  src/data/sponsor.test.js
  src/screens/HomeScreen/Header.test.js
  src/screens/HomeScreen/__snapshots__/Header.test.js.snap
  src/screens/HomeScreen/__snapshots__/component.test.js.snap
  src/screens/HomeScreen/__test-data.js
  src/screens/HomeScreen/component.test.js
  yarn.lock
Labels: ready for review

#371 Optimise event screen update
  src/reducers/__snapshots__/route.test.js.snap
  src/reducers/event-filters.js
  src/reducers/event-filters.test.js
  src/reducers/index.js
  src/reducers/route.js
  src/reducers/route.test.js
  src/selectors/event-filters.test.js
Labels: ready for review

#373 Fix e2e
  .circleci/config.yml
  yarn.lock
Labels: ready for review

#375 Asset refactor
  src/data/__snapshots__/image.test.js.snap
  src/data/__snapshots__/performance.test.js.snap
  src/data/__test-data.js
  src/data/image.js
  src/data/image.test.js
  src/data/performance.test.js
  src/reducers/__snapshots__/data.test.js.snap
  src/reducers/data.js
  src/reducers/data.test.js
  src/screens/SponsorScreen/SponsorLogo.js
  src/screens/SponsorScreen/SponsorLogo.test.js
  src/screens/SponsorScreen/SponsorLogoContainer.js
  src/screens/SponsorScreen/SponsorLogoContainer.test.js
  src/screens/SponsorScreen/__snapshots__/SponsorLogo.test.js.snap
  src/screens/SponsorScreen/__snapshots__/SponsorLogoContainer.test.js.snap
  src/screens/SponsorScreen/__snapshots__/component.test.js.snap
  src/screens/SponsorScreen/component.js
  src/screens/SponsorScreen/component.test.js
  src/screens/SponsorScreen/index.js
  src/selectors/event-filters.test.js
Labels: ready for review

#376 Event data refactor
  src/actions/event-filters.js
  src/components/CategoriesPills.js
  src/components/CategoriesPills.test.js
  src/components/CategoryPill.js
  src/components/EventList.js
  src/components/EventTile.js
  src/components/PerformanceList.js
  src/components/PerformanceList.test.js
  src/constants/event-categories.js
  src/data/__snapshots__/event.test.js.snap
  src/data/__test-data.js
  src/data/event-deprecated.js
  src/data/event-filters.js
  src/data/event.js
  src/data/event.test.js
  src/integrations/cms.js
  src/lib/decode.js
  src/lib/decode.test.js
  src/lib/maybe.js
  src/lib/maybe.test.js
  src/reducers/__snapshots__/data.test.js.snap
  src/reducers/data.js
  src/reducers/data.test.js
  src/reducers/index.js
  src/reducers/saved-events.js
  src/screens/CategoriesFilterScreen/Header.js
  src/screens/CategoriesFilterScreen/List.js
  src/screens/CategoriesFilterScreen/List.test.js
  src/screens/CategoriesFilterScreen/ListItem.js
  src/screens/CategoriesFilterScreen/ListItem.test.js
  src/screens/CategoriesFilterScreen/component.js
  src/screens/CategoriesFilterScreen/component.test.js
  src/screens/CategoriesFilterScreen/index.js
  src/screens/EventDetailsScreen/EventDescription.js
  src/screens/EventDetailsScreen/EventDescription.test.js
  src/screens/EventDetailsScreen/EventOverview.js
  src/screens/EventDetailsScreen/EventOverview.test.js
  src/screens/EventDetailsScreen/component.js
  src/screens/EventDetailsScreen/component.test.js
  src/screens/EventDetailsScreen/index.js
  src/screens/EventsScreen/FilterHeader.js
  src/screens/EventsScreen/FilterHeaderCategories.js
  src/screens/EventsScreen/FilterHeaderConnected.js
  src/screens/EventsScreen/component.js
  src/screens/EventsScreen/component.test.js
  src/screens/EventsScreen/index.js
  src/screens/FeaturedEventListScreen/component.js
  src/screens/FeaturedEventListScreen/index.js
  src/screens/HomeScreen/component.js
  src/screens/HomeScreen/component.test.js
  src/screens/HomeScreen/index.js
  src/screens/SavedEventListScreen/component.js
  src/screens/SavedEventListScreen/index.js
  src/selectors/basic-event-filters.js
  src/selectors/basic-event-filters.test.js
  src/selectors/event-filters.js
  src/selectors/event-filters.test.js
  src/selectors/event.js
  src/selectors/event.test.js
  src/selectors/events.js
Labels: ready for review

#384 Asset switcharoo
  src/components/EventCard.js
  src/components/EventCard.test.js
  src/components/EventList.js
  src/components/EventTile.js
  src/components/EventTile.test.js
  src/components/Image.js
  src/components/Image.test.js
  src/components/ImageBackground.js
  src/components/ImageBackground.test.js
  src/components/__snapshots__/EventCard.test.js.snap
  src/components/__snapshots__/EventList.test.js.snap
  src/components/__snapshots__/EventTile.test.js.snap
  src/components/__snapshots__/Image.test.js.snap
  src/components/__snapshots__/ImageBackground.test.js.snap
  src/data/__test-data.js
  src/data/asset.js
  src/data/get-asset-source.js
  src/data/get-asset-source.test.js
  src/integrations/cms.js
  src/reducers/__snapshots__/data.test.js.snap
  src/reducers/data.js
  src/reducers/data.test.js
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  src/screens/EventDetailsScreen/component.test.js
  src/screens/EventDetailsScreen/index.js
  src/screens/EventsScreen/__snapshots__/component.test.js.snap
  src/screens/EventsScreen/component.js
  src/screens/EventsScreen/component.test.js
  src/screens/EventsScreen/index.js
  src/screens/FeaturedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/FeaturedEventListScreen/component.js
  src/screens/FeaturedEventListScreen/component.test.js
  src/screens/FeaturedEventListScreen/index.js
  src/screens/HomeScreen/Header.js
  src/screens/HomeScreen/Header.test.js
  src/screens/HomeScreen/__snapshots__/Header.test.js.snap
  src/screens/HomeScreen/__snapshots__/component.test.js.snap
  src/screens/HomeScreen/component.js
  src/screens/HomeScreen/component.test.js
  src/screens/HomeScreen/index.js
  src/screens/SavedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/SavedEventListScreen/component.js
  src/screens/SavedEventListScreen/component.test.js
  src/screens/SavedEventListScreen/index.js
  src/screens/SponsorScreen/SponsorLogo.js
  src/screens/SponsorScreen/SponsorLogo.test.js
  src/screens/SponsorScreen/SponsorLogoContainer.js
  src/screens/SponsorScreen/SponsorLogoContainer.test.js
  src/screens/SponsorScreen/__snapshots__/SponsorLogo.test.js.snap
  src/screens/SponsorScreen/__snapshots__/SponsorLogoContainer.test.js.snap
  src/screens/SponsorScreen/__snapshots__/component.test.js.snap
  src/screens/SponsorScreen/component.js
  src/screens/SponsorScreen/component.test.js
  src/screens/SponsorScreen/index.js
  src/selectors/events.js
  src/selectors/events.test.js
Labels: ready for review

#362 Parade map
  e2e/firstTest.spec.js
  ios/PrideLondonApp.xcodeproj/project.pbxproj
  ios/PrideLondonApp/Info.plist
  package.json
  scripts/google-maps-ios.sh
  src/Navigation.js
  src/constants/parade-coordinates.js
  src/constants/routes.js
  src/constants/text.js
  src/screens/EventDetailsScreen/__snapshots__/EventMap.test.js.snap
  src/screens/ParadeInformationScreen/__snapshots__/component.test.js.snap
  src/screens/ParadeInformationScreen/component.js
  src/screens/ParadeMapScreen/__snapshots__/component.test.js.snap
  src/screens/ParadeMapScreen/component.js
  src/screens/ParadeMapScreen/component.test.js
  src/screens/ParadeMapScreen/index.js
  src/screens/ParadeNavigator/__snapshots__/component.test.js.snap
  src/screens/ParadeNavigator/component.js
  src/screens/ParadeNavigator/component.test.js
  src/screens/ParadeNavigator/index.js
  yarn.lock
Labels: qa approved, ready for review

#385 Hook up new event model to EventDetails Screen
  flow-typed/npm/reselect_v3.x.x.js
  package.json
  src/components/PerformanceList.js
  src/components/PerformanceList.test.js
  src/components/__snapshots__/Image.test.js.snap
  src/components/__snapshots__/ImageBackground.test.js.snap
  src/components/__snapshots__/PerformanceList.test.js.snap
  src/data/__snapshots__/event.test.js.snap
  src/data/__snapshots__/header-banner.test.js.snap
  src/data/__snapshots__/image.test.js.snap
  src/data/__snapshots__/performance.test.js.snap
  src/data/__snapshots__/sponsor.test.js.snap
  src/data/__test-data.js
  src/data/event.js
  src/data/formatters.js
  src/reducers/__snapshots__/data.test.js.snap
  src/reducers/data.js
  src/reducers/data.test.js
  src/screens/CategoriesFilterScreen/index.js
  src/screens/EventDetailsScreen/EventContact.js
  src/screens/EventDetailsScreen/EventDescription.js
  src/screens/EventDetailsScreen/EventDescription.test.js
  src/screens/EventDetailsScreen/EventOverview.js
  src/screens/EventDetailsScreen/EventOverview.test.js
  src/screens/EventDetailsScreen/__snapshots__/EventDescription.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/EventOverview.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  src/screens/EventDetailsScreen/component.test.js
  src/screens/EventDetailsScreen/index.js
  src/screens/EventsScreen/DateRangePickerDialogConnected.js
  src/screens/EventsScreen/index.js
  src/screens/FeaturedEventListScreen/index.js
  src/screens/FilterScreen/index.js
  src/screens/HomeScreen/__snapshots__/Header.test.js.snap
  src/screens/HomeScreen/__snapshots__/component.test.js.snap
  src/screens/HomeScreen/component.test.js
  src/screens/HomeScreen/index.js
  src/screens/SavedEventListScreen/index.js
  src/selectors/__snapshots__/data.test.js.snap
  src/selectors/basic-event-filters.js
  src/selectors/data.js
  src/selectors/data.test.js
  src/selectors/event-deprecated.js
  src/selectors/event-deprecated.test.js
  src/selectors/events-deprecated.js
  src/selectors/events-deprecated.test.js
  src/selectors/index.js
  src/selectors/performance.js
  src/selectors/performance.test.js
  yarn.lock
Labels: ready for review

#359 Release pipeline
  .gitignore
  android/fastlane/Fastfile
  android/fastlane/README.md
  android/fastlane/metadata/android/en-GB/changelogs/239.txt
  android/fastlane/metadata/android/en-GB/changelogs/241.txt
  android/fastlane/metadata/android/en-GB/changelogs/248.txt
  android/fastlane/metadata/android/en-GB/full_description.txt
  android/fastlane/metadata/android/en-GB/images/icon.png
  android/fastlane/metadata/android/en-GB/short_description.txt
  android/fastlane/metadata/android/en-GB/title.txt
  android/fastlane/metadata/android/en-GB/video.txt
  ios/fastlane/Deliverfile
  ios/fastlane/Fastfile
  ios/fastlane/README.md
  ios/fastlane/metadata/app_icon.jpg
  ios/fastlane/metadata/copyright.txt
  ios/fastlane/metadata/en-GB/description.txt
  ios/fastlane/metadata/en-GB/keywords.txt
  ios/fastlane/metadata/en-GB/marketing_url.txt
  ios/fastlane/metadata/en-GB/name.txt
  ios/fastlane/metadata/en-GB/privacy_url.txt
  ios/fastlane/metadata/en-GB/promotional_text.txt
  ios/fastlane/metadata/en-GB/release_notes.txt
  ios/fastlane/metadata/en-GB/subtitle.txt
  ios/fastlane/metadata/en-GB/support_url.txt
  ios/fastlane/metadata/primary_category.txt
  ios/fastlane/metadata/primary_first_sub_category.txt
  ios/fastlane/metadata/primary_second_sub_category.txt
  ios/fastlane/metadata/review_information/demo_password.txt
  ios/fastlane/metadata/review_information/demo_user.txt
  ios/fastlane/metadata/review_information/email_address.txt
  ios/fastlane/metadata/review_information/first_name.txt
  ios/fastlane/metadata/review_information/last_name.txt
  ios/fastlane/metadata/review_information/notes.txt
  ios/fastlane/metadata/review_information/phone_number.txt
  ios/fastlane/metadata/secondary_category.txt
  ios/fastlane/metadata/secondary_first_sub_category.txt
  ios/fastlane/metadata/secondary_second_sub_category.txt
  ios/fastlane/metadata/trade_representative_contact_information/address_line1.txt
  ios/fastlane/metadata/trade_representative_contact_information/address_line2.txt
  ios/fastlane/metadata/trade_representative_contact_information/address_line3.txt
  ios/fastlane/metadata/trade_representative_contact_information/city_name.txt
  ios/fastlane/metadata/trade_representative_contact_information/country.txt
  ios/fastlane/metadata/trade_representative_contact_information/email_address.txt
  ios/fastlane/metadata/trade_representative_contact_information/first_name.txt
  ios/fastlane/metadata/trade_representative_contact_information/is_displayed_on_app_store.txt
  ios/fastlane/metadata/trade_representative_contact_information/last_name.txt
  ios/fastlane/metadata/trade_representative_contact_information/phone_number.txt
  ios/fastlane/metadata/trade_representative_contact_information/postal_code.txt
  ios/fastlane/metadata/trade_representative_contact_information/state.txt
  ios/fastlane/metadata/trade_representative_contact_information/trade_name.txt
Labels: ready for review

#393 FeaturedEvents data refactor
  src/data/__snapshots__/featured-events.test.js.snap
  src/data/__test-data.js
  src/data/featured-events.js
  src/data/featured-events.test.js
  src/reducers/__snapshots__/data.test.js.snap
  src/reducers/data.js
  src/reducers/data.test.js
  src/selectors/data.test.js
  src/selectors/event-filters.test.js
Labels: ready for review

#394 Refactor refreshing and loading selectors
  src/screens/EventsScreen/index.js
  src/screens/HomeScreen/index.js
  src/screens/SavedEventListScreen/index.js
  src/selectors/data.js
  src/selectors/data.test.js
  src/selectors/events-deprecated.js
  src/selectors/events-deprecated.test.js
Labels: ready for review

#388 Play store images
  android/fastlane/metadata/android/en-GB/images/featureGraphic.jpg
  android/fastlane/metadata/android/en-GB/images/icon.png
  android/fastlane/metadata/android/en-GB/images/phoneScreenshots/PlayStoreAssets1.jpg
  android/fastlane/metadata/android/en-GB/images/phoneScreenshots/PlayStoreAssets2.jpg
  android/fastlane/metadata/android/en-GB/images/phoneScreenshots/PlayStoreAssets3.jpg
  android/fastlane/metadata/android/en-GB/images/phoneScreenshots/PlayStoreAssets4.jpg
  android/fastlane/metadata/android/en-GB/images/phoneScreenshots/PlayStoreAssets5.jpg
Labels: ready for review

#396 Bump to v1.0.8
  android/app/build.gradle
  ios/PrideLondonApp/Info.plist
  ios/PrideLondonAppTests/Info.plist
  package.json
Labels: ready for review

#381 App store content changes
  ios/fastlane/metadata/copyright.txt
  ios/fastlane/metadata/en-GB/description.txt
  ios/fastlane/metadata/en-GB/release_notes.txt
Labels: ready for review

#380 Play Store content changes
  android/fastlane/metadata/android/en-GB/full_description.txt
  android/fastlane/metadata/android/en-GB/short_description.txt
Labels: ready for review

#395 Parade map style tweaks
  src/components/TopTabBar.js
  src/components/TopTabBar.test.js
  src/components/__snapshots__/TopTabBar.test.js.snap
  src/constants/colors.js
  src/screens/ParadeNavigator/component.js
Labels: ready for review

#398 Refactor event filter selectors
  src/screens/CategoriesFilterScreen/index.js
  src/screens/EventsScreen/DateRangePickerDialogConnected.js
  src/screens/EventsScreen/index.js
  src/screens/FilterScreen/index.js
  src/selectors/event-filters.js
  src/selectors/event-filters.test.js
  src/selectors/events-deprecated.js
  src/selectors/events-deprecated.test.js
  src/selectors/index.js
Labels: ready for review

#399 Default/placeholder location card
  assets/images/locationCardDefault.png
  assets/images/locationCardDefault@2x.png
  assets/images/locationCardDefault@3x.png
  src/constants/colors.js
  src/screens/ParadeMapScreen/LocationCard.js
  src/screens/ParadeMapScreen/LocationCard.test.js
  src/screens/ParadeMapScreen/__snapshots__/LocationCard.test.js.snap
  src/screens/ParadeMapScreen/__snapshots__/component.test.js.snap
  src/screens/ParadeMapScreen/component.js
Labels: qa approved

#400 v2.0.0
  android/app/build.gradle
  ios/PrideLondonApp/Info.plist
  ios/PrideLondonAppTests/Info.plist
  package.json
Labels: ready for review

#407 Changelog for android versionCode 7178
  android/fastlane/metadata/android/en-GB/changelogs/7178.txt
  android/fastlane/metadata/android/en-GB/short_description.txt
Labels: ready for review

#411 v2.0.1
  android/app/build.gradle
  ios/PrideLondonApp/Info.plist
  ios/PrideLondonAppTests/Info.plist
  package.json
Labels: ready for review

#406 Minor changes to iOS release process
  ios/fastlane/Deliverfile
  ios/fastlane/Fastfile
  ios/fastlane/README.md
Labels: ready for review

#409 Fix repeat save event animation and vibration
  src/Navigation.js
  src/components/OnlyUpdateWhenFocused.js
  src/components/OnlyUpdateWhenFocused.test.js
  src/components/SaveEventButton.js
  src/components/SaveEventButton.test.js
  src/components/__snapshots__/SaveEventButton.test.js.snap
  src/lib/navigation.js
  src/screens/EventDetailsScreen/component.js
  src/screens/EventsScreen/component.js
  src/screens/EventsScreen/component.test.js
  src/screens/EventsScreen/index.js
  src/screens/FeaturedEventListScreen/component.js
  src/screens/FilterScreen/component.js
  src/screens/HomeScreen/component.js
  src/screens/HomeScreen/component.test.js
  src/screens/HomeScreen/index.js
  src/screens/ParadeMapScreen/component.js
  src/screens/ParadeMapScreen/component.test.js
  src/screens/ParadeNavigator/__snapshots__/component.test.js.snap
  src/screens/ParadeNavigator/component.js
  src/screens/ParadeNavigator/component.test.js
  src/screens/ParadeNavigator/index.js
  src/screens/SavedEventListScreen/component.js
  src/screens/SavedEventListScreen/component.test.js
  src/screens/SavedEventListScreen/index.js
Labels: ready for review, ready for test

#413 Fix incorrect parade day
  src/constants/text.js
  src/screens/ParadeInformationScreen/__snapshots__/component.test.js.snap
Labels: ready for review

#415 Refactor event categories
  src/actions/event-filters.js
  src/components/CategoriesPills.js
  src/components/CategoriesPills.test.js
  src/components/CategoryPill.js
  src/components/EventTile.js
  src/constants/event-categories.js
  src/data/event-deprecated.js
  src/data/event-filters.js
  src/data/event.js
  src/screens/CategoriesFilterScreen/Header.js
  src/screens/CategoriesFilterScreen/List.js
  src/screens/CategoriesFilterScreen/List.test.js
  src/screens/CategoriesFilterScreen/ListItem.js
  src/screens/CategoriesFilterScreen/ListItem.test.js
  src/screens/CategoriesFilterScreen/__snapshots__/component.test.js.snap
  src/screens/CategoriesFilterScreen/component.js
  src/screens/CategoriesFilterScreen/component.test.js
  src/screens/CategoriesFilterScreen/index.js
  src/screens/EventsScreen/FilterHeader.js
  src/screens/EventsScreen/FilterHeaderCategories.js
  src/screens/EventsScreen/FilterHeaderConnected.js
  src/screens/EventsScreen/component.js
  src/screens/EventsScreen/index.js
  src/selectors/basic-event-filters.js
  src/selectors/basic-event-filters.test.js
Labels: ready for review

#426 Use local version of detox
  .circleci/config.yml
Labels: ready for review

#425 Update iOS screenshot
  ios/fastlane/screenshots/en-GB/AppStoreAssets5.jpg
Labels: ready for review

#429 make active tab indicator full width
  src/components/TopTabBar.js
  src/components/__snapshots__/TopTabBar.test.js.snap
Labels: qa approved, ready for review

#421 Refactor rest of screens to use new event model
  src/components/EventList.js
  src/components/EventList.test.js
  src/components/__snapshots__/EventCard.test.js.snap
  src/components/__snapshots__/EventList.test.js.snap
  src/components/__snapshots__/EventTile.test.js.snap
  src/data/__snapshots__/event.test.js.snap
  src/data/__snapshots__/featured-events.test.js.snap
  src/data/__snapshots__/field-ref.test.js.snap
  src/data/__snapshots__/header-banner.test.js.snap
  src/data/__snapshots__/sponsor.test.js.snap
  src/data/__test-data.js
  src/data/event-deprecated.js
  src/data/event.js
  src/data/formatters.js
  src/integrations/cms.js
  src/reducers/__snapshots__/data.test.js.snap
  src/reducers/data.js
  src/reducers/data.test.js
  src/reducers/index.js
  src/reducers/saved-events.js
  src/screens/CategoriesFilterScreen/index.test.js
  src/screens/DateFilterScreen/index.js
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventsScreen/FilterHeaderConnected.js
  src/screens/EventsScreen/__snapshots__/component.test.js.snap
  src/screens/EventsScreen/component.js
  src/screens/EventsScreen/component.test.js
  src/screens/EventsScreen/index.js
  src/screens/FeaturedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/FeaturedEventListScreen/component.js
  src/screens/FeaturedEventListScreen/index.js
  src/screens/FilterScreen/index.js
  src/screens/HomeScreen/__snapshots__/component.test.js.snap
  src/screens/HomeScreen/component.js
  src/screens/HomeScreen/component.test.js
  src/screens/HomeScreen/index.js
  src/screens/SavedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/SavedEventListScreen/component.js
  src/screens/SavedEventListScreen/index.js
  src/screens/SponsorScreen/__snapshots__/SponsorLogo.test.js.snap
  src/selectors/__snapshots__/data.test.js.snap
  src/selectors/basic-event-filters.js
  src/selectors/basic-event-filters.test.js
  src/selectors/data.js
  src/selectors/data.test.js
  src/selectors/event-deprecated.js
  src/selectors/event-deprecated.test.js
  src/selectors/event-filters.js
  src/selectors/event-filters.test.js
  src/selectors/event.js
  src/selectors/event.test.js
  src/selectors/events-deprecated.js
  src/selectors/events-deprecated.test.js
  src/selectors/index.js
  src/selectors/saved-events.js
  src/selectors/saved-events.test.js
Labels: ready for review

#428 Parade typos
  src/constants/text.js
  src/screens/ParadeInformationScreen/__snapshots__/component.test.js.snap
Labels: qa approved, ready for review

#427 Calendar styling fixes
  src/screens/DateFilterScreen/DateRangePicker.js
  src/screens/DateFilterScreen/DateRangePickerDay.js
  src/screens/DateFilterScreen/DateRangePickerDay.test.js
  src/screens/DateFilterScreen/__snapshots__/DateRangePicker.test.js.snap
  src/screens/DateFilterScreen/__snapshots__/DateRangePickerDay.test.js.snap
  src/screens/DateFilterScreen/component.js
  src/screens/DateFilterScreen/component.test.js
Labels: ready for review

#430 Stop filtering saved events and featured events with event filters
  src/screens/SavedEventListScreen/index.js
  src/selectors/index.js
Labels: ready for review

#437 fix typo in readme
  README.md
Labels: ready for review

#434 Update android screenshot
  android/fastlane/metadata/android/en-GB/images/phoneScreenshots/PlayStoreAssets5.jpg
Labels: ready for review

#440 v2.0.2
  android/app/build.gradle
  ios/PrideLondonApp/Info.plist
  ios/PrideLondonAppTests/Info.plist
  package.json
Labels: ready for review

#442 Latest changelog for Android
  android/fastlane/metadata/android/en-GB/changelogs/7566.txt
Labels: ready for review

#451 Rendering optimisation take 2
  src/Navigation.js
  src/components/OnlyUpdateWhenFocused.js
  src/components/OnlyUpdateWhenFocused.test.js
  src/components/WithIsFocused.js
  src/components/WithIsFocused.test.js
  src/screens/CategoriesFilterScreen/index.js
  src/screens/CategoriesFilterScreen/index.test.js
  src/screens/DateFilterScreen/index.js
  src/screens/DateFilterScreen/index.test.js
  src/screens/EventDetailsScreen/index.js
  src/screens/EventsScreen/index.js
  src/screens/EventsScreen/index.test.js
  src/screens/FeaturedEventListScreen/index.js
  src/screens/FeaturedEventListScreen/index.test.js
  src/screens/FilterScreen/index.js
  src/screens/HomeScreen/index.js
  src/screens/HomeScreen/index.test.js
  src/screens/SavedEventListScreen/component.js
  src/screens/SavedEventListScreen/index.js
  src/screens/SavedEventListScreen/index.test.js
  src/screens/SponsorScreen/index.js
  src/screens/SponsorScreen/index.test.js
Labels: qa approved, ready for review

#435 Reset all filters button on Events page
  src/actions/event-filters.js
  src/components/EventList.js
  src/constants/text.js
  src/screens/EventsScreen/FilterHeader.js
  src/screens/EventsScreen/FilterHeader.test.js
  src/screens/EventsScreen/FilterHeaderConnected.js
  src/screens/EventsScreen/FilterHeaderConnected.test.js
  src/screens/EventsScreen/ResetAllFiltersButton.js
  src/screens/EventsScreen/ResetAllFiltersButton.test.js
  src/screens/EventsScreen/__snapshots__/FilterHeader.test.js.snap
  src/screens/EventsScreen/__snapshots__/FilterHeaderConnected.test.js.snap
  src/screens/EventsScreen/__snapshots__/ResetAllFiltersButton.test.js.snap
  src/screens/EventsScreen/__snapshots__/component.test.js.snap
  src/screens/EventsScreen/component.js
  src/screens/EventsScreen/component.test.js
Labels: qa approved, ready for review

#473 Potential Fix for Android Crashing Maps
  src/screens/ParadeMapScreen/__snapshots__/component.test.js.snap
  src/screens/ParadeMapScreen/component.js
  src/screens/ParadeMapScreen/component.test.js
  src/screens/ParadeMapScreen/index.js
Labels: ready for review

#471 Add parade group data to state
  src/data/__snapshots__/parade-group.test.js.snap
  src/data/__test-data.js
  src/data/parade-group.js
  src/data/parade-group.test.js
  src/reducers/__snapshots__/data.test.js.snap
  src/reducers/data.js
  src/reducers/data.test.js
  src/selectors/data.test.js
Labels: ready for review

#465 add links to the app in the store
  README.md
Labels: ready for review

#482 Reduce build log noise
  .circleci/config.yml
  ios/fastlane/Fastfile
  package.json
Labels: ready for review

#474 Add ParadeGroupsScreen
  e2e/parade.spec.js
  src/Navigation.js
  src/components/TopTabBar.js
  src/components/__snapshots__/TopTabBar.test.js.snap
  src/constants/routes.js
  src/constants/text.js
  src/data/__snapshots__/parade-group.test.js.snap
  src/data/__test-data.js
  src/data/parade-group.js
  src/data/parade-group.test.js
  src/screens/ParadeGroupsScreen/ParadeGroupDetails.js
  src/screens/ParadeGroupsScreen/ParadeGroupDetails.test.js
  src/screens/ParadeGroupsScreen/ParadeGroupList.js
  src/screens/ParadeGroupsScreen/ParadeGroupList.test.js
  src/screens/ParadeGroupsScreen/__snapshots__/ParadeGroupDetails.test.js.snap
  src/screens/ParadeGroupsScreen/__snapshots__/ParadeGroupList.test.js.snap
  src/screens/ParadeGroupsScreen/__snapshots__/component.test.js.snap
  src/screens/ParadeGroupsScreen/component.js
  src/screens/ParadeGroupsScreen/component.test.js
  src/screens/ParadeGroupsScreen/index.js
  src/screens/ParadeInformationScreen/__snapshots__/component.test.js.snap
Labels: ready for review, ready for test

#466 Change VoiceOver checkbox behaviour
  ios/PrideLondonApp.xcodeproj/project.pbxproj
  package.json
  src/components/CheckBox.js
  src/components/Touchable.android.js
  src/components/Touchable.android.test.js
  src/components/Touchable.ios.js
  src/components/__snapshots__/CheckBox.test.js.snap
  src/data/accessibility.android.js
  src/data/accessibility.ios.js
  src/data/accessibility.test.js
  src/screens/CategoriesFilterScreen/ListItem.js
  src/screens/CategoriesFilterScreen/__snapshots__/ListItem.test.js.snap
  yarn.lock
Labels: ready for test

#408 Showing user location on Parade map
  android/app/src/main/AndroidManifest.xml
  assets/images/location-active.android.png
  assets/images/location-active.ios.png
  assets/images/location-active@2x.android.png
  assets/images/location-active@2x.ios.png
  assets/images/location-active@3x.android.png
  assets/images/location-active@3x.ios.png
  assets/images/location-inactive.android.png
  assets/images/location-inactive.ios.png
  assets/images/location-inactive@2x.android.png
  assets/images/location-inactive@2x.ios.png
  assets/images/location-inactive@3x.android.png
  assets/images/location-inactive@3x.ios.png
  ios/PrideLondonApp.xcodeproj/project.pbxproj
  ios/PrideLondonApp/Info.plist
  package.json
  src/constants/parade-coordinates.js
  src/lib/position.js
  src/lib/position.test.js
  src/screens/ParadeMapScreen/Map.js
  src/screens/ParadeMapScreen/Map.test.js
  src/screens/ParadeMapScreen/__snapshots__/Map.test.js.snap
  src/screens/ParadeMapScreen/__snapshots__/component.test.js.snap
  src/screens/ParadeMapScreen/component.js
  yarn.lock
Labels: ready for review

#499 Update dev dependencies
  package.json
  src/components/Collapsible.test.js
  src/components/__snapshots__/EventList.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/FilterScreen/__snapshots__/Header.test.js.snap
  src/screens/ParadeGroupsScreen/__snapshots__/ParadeGroupList.test.js.snap
  yarn.lock
Labels: ready for review

#504 Migrate to detox v8
  .circleci/config.yml
  .eslintrc
  .gitignore
  e2e/events.spec.js
  e2e/home.spec.js
  e2e/init.js
  e2e/parade.spec.js
  e2e/saved-events.spec.js
  e2e/support-us.spec.js
  package.json
  yarn.lock
Labels: ready for review

#483 Splash Screen no. 3
  assets/images/logo.png
  assets/images/logo@2x.png
  assets/images/logo@3x.png
  src/App.js
  src/__snapshots__/App.test.js.snap
  src/actions/splash-screen.js
  src/reducers/splash-screen.js
  src/reducers/splash-screen.test.js
  src/screens/SplashScreen/Welcome.js
  src/screens/SplashScreen/Welcome.test.js
  src/screens/SplashScreen/__snapshots__/Welcome.test.js.snap
  src/screens/SplashScreen/__snapshots__/component.test.js.snap
  src/screens/SplashScreen/component.js
  src/screens/SplashScreen/component.test.js
  src/screens/SplashScreen/index.js
Labels: ready for review

#534 Amenities on Parade Map
  assets/images/amenityIconFirstAid.png
  assets/images/amenityIconFirstAid@2x.png
  assets/images/amenityIconFirstAid@3x.png
  assets/images/amenityIconToilet.png
  assets/images/amenityIconToilet@2x.png
  assets/images/amenityIconToilet@3x.png
  src/constants/parade-coordinates.js
  src/data/__test-data.js
  src/data/amenity.js
  src/reducers/__snapshots__/data.test.js.snap
  src/reducers/data.js
  src/reducers/data.test.js
  src/screens/ParadeMapScreen/AmenityMarkers.js
  src/screens/ParadeMapScreen/AmenityMarkers.test.js
  src/screens/ParadeMapScreen/Map.js
  src/screens/ParadeMapScreen/Map.test.js
  src/screens/ParadeMapScreen/StageMarkers.js
  src/screens/ParadeMapScreen/StageMarkers.test.js
  src/screens/ParadeMapScreen/TerminalMarkers.js
  src/screens/ParadeMapScreen/TerminalMarkers.test.js
  src/screens/ParadeMapScreen/__snapshots__/AmenityMarkers.test.js.snap
  src/screens/ParadeMapScreen/__snapshots__/Map.test.js.snap
  src/screens/ParadeMapScreen/__snapshots__/StageMarkers.test.js.snap
  src/screens/ParadeMapScreen/__snapshots__/TerminalMarkers.test.js.snap
  src/screens/ParadeMapScreen/__snapshots__/component.test.js.snap
  src/screens/ParadeMapScreen/component.js
  src/screens/ParadeMapScreen/component.test.js
  src/screens/ParadeMapScreen/index.js
  src/selectors/data.js
  src/selectors/data.test.js
  src/selectors/index.js
Labels: ready for review

#531 Native splash screens
  android/app/src/main/res/drawable/background_splash.xml
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/mipmap-hdpi/icon.png
  android/app/src/main/res/mipmap-hdpi/logo.png
  android/app/src/main/res/mipmap-hdpi/splash.png
  android/app/src/main/res/mipmap-mdpi/icon.png
  android/app/src/main/res/mipmap-mdpi/logo.png
  android/app/src/main/res/mipmap-mdpi/splash.png
  android/app/src/main/res/mipmap-xhdpi/icon.png
  android/app/src/main/res/mipmap-xhdpi/logo.png
  android/app/src/main/res/mipmap-xhdpi/splash.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  assets/images/splash.png
  assets/images/splash@2x.png
  assets/images/splash@3x.png
  ios/PrideLondonApp/Base.lproj/LaunchScreen.xib
  ios/PrideLondonApp/Images.xcassets/SplashIcon.imageset/logo.png
  ios/PrideLondonApp/Images.xcassets/SplashIcon.imageset/logo@2x.png
  ios/PrideLondonApp/Images.xcassets/SplashIcon.imageset/logo@3x.png
  ios/PrideLondonApp/Images.xcassets/WelcomeLogo.imageset/Contents.json
  ios/PrideLondonApp/Images.xcassets/WelcomeLogo.imageset/logo.png
  ios/PrideLondonApp/Images.xcassets/WelcomeLogo.imageset/logo@2x.png
  ios/PrideLondonApp/Images.xcassets/WelcomeLogo.imageset/logo@3x.png
  ios/PrideLondonApp/Images.xcassets/WelcomeText.imageset/Contents.json
  ios/PrideLondonApp/Images.xcassets/WelcomeText.imageset/splash.png
  ios/PrideLondonApp/Images.xcassets/WelcomeText.imageset/splash@2x.png
  ios/PrideLondonApp/Images.xcassets/WelcomeText.imageset/splash@3x.png
  ios/PrideLondonApp/Info.plist
  src/screens/SplashScreen/Welcome.js
  src/screens/SplashScreen/__snapshots__/Welcome.test.js.snap
  src/screens/SplashScreen/component.js
Labels: ready for review

#530 Welcome Screen: Bad Connection
  package.json
  src/actions/data.js
  src/actions/data.test.js
  src/constants/text.js
  src/reducers/__snapshots__/data.test.js.snap
  src/reducers/data.js
  src/reducers/data.test.js
  src/screens/ParadeGroupsScreen/component.js
  src/screens/SplashScreen/BadConnection.js
  src/screens/SplashScreen/BadConnection.test.js
  src/screens/SplashScreen/Welcome.js
  src/screens/SplashScreen/Welcome.test.js
  src/screens/SplashScreen/__snapshots__/BadConnection.test.js.snap
  src/screens/SplashScreen/__snapshots__/Welcome.test.js.snap
  src/screens/SplashScreen/__snapshots__/component.test.js.snap
  src/screens/SplashScreen/component.js
  src/screens/SplashScreen/component.test.js
  src/screens/SplashScreen/index.js
  src/selectors/data.test.js
Labels: ready for review
