Repository redbadger/pride-london-app, pull requests merged in 2018-05, with the labels that each got.

#187 Clean up CircleCI yaml
  .circleci/config.yml
Labels: ready for review

#191 Persist favourited events to local storage
  src/actions/saved-events.js
  src/actions/saved-events.test.js
  src/index.js
  src/integrations/storage.js
  src/integrations/storage.test.js
  src/reducers/__snapshots__/saved-events.test.js.snap
  src/reducers/saved-events.js
  src/reducers/saved-events.test.js
Labels: ready for review

#194 iTunes Connect query without app version is too vague
  android/app/build.gradle
  ios/PrideLondonApp/Info.plist
  ios/PrideLondonAppTests/Info.plist
  ios/fastlane/Fastfile
  package.json
Labels: ready for review

#200 Fix class path
  android/app/src/main/java/org/prideinlondon/festival/MainActivity.java
  android/app/src/main/java/org/prideinlondon/festival/MainApplication.java
Labels: ready for review

#201 Saved events: no events screen, accessibility labels for the 💚 button
  assets/images/howToSaveEvents.png
  assets/images/howToSaveEvents@2x.png
  assets/images/howToSaveEvents@3x.png
  assets/images/save.png
  assets/images/save@2x.png
  assets/images/save@3x.png
  src/components/SaveEventButton.js
  src/components/SaveEventButton.test.js
  src/components/__snapshots__/SaveEventButton.test.js.snap
  src/constants/text.js
  src/screens/SavedEventListScreen/NoSavedEvents.js
  src/screens/SavedEventListScreen/NoSavedEvents.test.js
  src/screens/SavedEventListScreen/__snapshots__/NoSavedEvents.test.js.snap
  src/screens/SavedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/SavedEventListScreen/component.js
  src/screens/SavedEventListScreen/component.test.js
Labels: ready for review

#209 Saved events screen: routing
  src/App.js
Labels: ready for review

#198 Update favourite animation with shorter lead in
  android/app/build.gradle
  android/app/src/main/java/org/prideinlondon/festival/MainApplication.java
  android/settings.gradle
  assets/animations/save-event-dark.json
  assets/animations/save-event-light.json
  ios/PrideLondonApp.xcodeproj/project.pbxproj
  package.json
  src/components/SaveEventButton.js
  src/components/SaveEventButton.test.js
  src/components/__snapshots__/SaveEventButton.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  yarn.lock
Labels: ready for review

#214 Refactor common header
  src/components/Header.js
  src/components/Header.test.js
  src/components/__snapshots__/Header.test.js.snap
  src/constants/text.js
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  src/screens/FeaturedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/FeaturedEventListScreen/component.js
  src/screens/SavedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/SavedEventListScreen/component.js
  src/screens/SponsorScreen/__snapshots__/component.test.js.snap
  src/screens/SponsorScreen/component.js
  src/screens/SponsorScreen/component.test.js
  src/screens/SupportUsScreen/__snapshots__/index.test.js.snap
  src/screens/SupportUsScreen/index.js
Labels: ready for review

#208 E2E 🔥
  .circleci/config.yml
  e2e/firstTest.spec.js
  e2e/helpers.js
  e2e/init.js
  package.json
Labels: ready for review

#222 Use CI build number for iOS release builds
  .circleci/config.yml
  ios/fastlane/Fastfile
Labels: ready for review

#218 Saved events screen: accessibility label for the heart icon
  src/screens/SavedEventListScreen/NoSavedEvents.js
  src/screens/SavedEventListScreen/__snapshots__/NoSavedEvents.test.js.snap
Labels: ready for review

#219 Display List of Acts: UI Issues
  src/components/EventCard.js
  src/components/Performance.js
  src/components/PerformanceList.js
  src/components/SectionDivider.js
  src/components/SectionDivider.test.js
  src/components/SectionHeader.js
  src/components/__snapshots__/EventList.test.js.snap
  src/components/__snapshots__/Performance.test.js.snap
  src/components/__snapshots__/PerformanceList.test.js.snap
  src/components/__snapshots__/SectionDivider.test.js.snap
  src/components/__snapshots__/SectionHeader.test.js.snap
  src/constants/colors.js
  src/data/formatters.js
  src/data/formatters.test.js
  src/screens/EventDetailsScreen/EventOverview.js
  src/screens/EventDetailsScreen/__snapshots__/EventOverview.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
Labels: ready for review

#229 Set new App Icon for release
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-60x60@1x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-76x76@3x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-Small-50x50@1x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/Icon-Small-50x50@2x.png
  ios/PrideLondonApp/Images.xcassets/AppIcon.appiconset/ItunesArtwork@2x.png
Labels: ready for review

#127 Applying UI design to Home Page Featured Events
  src/components/CategoryPill.js
  src/components/EventTile.js
  src/components/EventTile.test.js
  src/components/__snapshots__/EventTile.test.js.snap
  src/constants/text.js
  src/data/event.js
  src/screens/HomeScreen/__snapshots__/component.test.js.snap
  src/screens/HomeScreen/component.js
  src/screens/HomeScreen/component.test.js
Labels: ready for review

#225 Adding min-heights to a bunch of stuff on the event listing.
  src/components/EventCard.js
  src/components/SectionHeader.js
  src/components/__snapshots__/EventCard.test.js.snap
  src/components/__snapshots__/EventList.test.js.snap
  src/components/__snapshots__/SectionHeader.test.js.snap
Labels: accessibility, qa approved, ready for review

#227 Generate .env per job and use release keys for release jobs
  .circleci/config.yml
Labels: ready for review

#236 Actually set release key values
  .circleci/config.yml
Labels: ready for review

#239 Refactor get asset url
  src/components/EventCard.js
  src/components/EventCard.test.js
  src/components/EventList.js
  src/components/EventList.test.js
  src/components/EventTile.js
  src/components/EventTile.test.js
  src/components/__snapshots__/EventCard.test.js.snap
  src/components/__snapshots__/EventList.test.js.snap
  src/components/__snapshots__/EventTile.test.js.snap
  src/data/event.js
  src/data/field-ref.js
  src/data/get-asset-size.js
  src/data/get-asset-source.js
  src/data/get-asset-url.js
  src/data/localized-field-ref.js
  src/data/sponsor.js
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  src/screens/EventDetailsScreen/component.test.js
  src/screens/EventDetailsScreen/index.js
  src/screens/EventsScreen/__snapshots__/component.test.js.snap
  src/screens/EventsScreen/component.js
  src/screens/EventsScreen/component.test.js
  src/screens/EventsScreen/index.js
  src/screens/FeaturedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/FeaturedEventListScreen/component.js
  src/screens/FeaturedEventListScreen/component.test.js
  src/screens/FeaturedEventListScreen/index.js
  src/screens/HomeScreen/__snapshots__/component.test.js.snap
  src/screens/HomeScreen/component.js
  src/screens/HomeScreen/component.test.js
  src/screens/HomeScreen/index.js
  src/screens/SavedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/SavedEventListScreen/component.js
  src/screens/SavedEventListScreen/component.test.js
  src/screens/SavedEventListScreen/index.js
  src/screens/SponsorScreen/SponsorLogo.js
  src/screens/SponsorScreen/SponsorLogo.test.js
  src/screens/SponsorScreen/SponsorLogoContainer.js
  src/screens/SponsorScreen/SponsorLogoContainer.test.js
  src/screens/SponsorScreen/__snapshots__/SponsorLogoContainer.test.js.snap
  src/screens/SponsorScreen/__snapshots__/component.test.js.snap
  src/screens/SponsorScreen/component.js
  src/screens/SponsorScreen/component.test.js
  src/screens/SponsorScreen/index.js
Labels: ready for review

#240 Fixes for category filter
  src/actions/event-filters.js
  src/actions/event-filters.test.js
  src/components/CategoriesPills.js
  src/components/CategoriesPills.test.js
  src/components/CategoryPill.js
  src/components/FilterHeaderCategories.js
  src/components/NavigationTabBar.js
  src/components/NavigationTabBar.test.js
  src/components/__snapshots__/CategoryPill.test.js.snap
  src/components/__snapshots__/FilterHeaderCategories.test.js.snap
  src/reducers/event-filters.js
  src/reducers/event-filters.test.js
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  src/screens/EventDetailsScreen/component.test.js
  src/screens/EventDetailsScreen/index.js
Labels: ready for review

#244 Run e2e tests against a release build
  .circleci/config.yml
  ios/PrideLondonApp.xcodeproj/project.pbxproj
  ios/PrideLondonApp/Info.plist
  package.json
Labels: ready for review

#184 Filter header styling updates
  src/components/FilterHeader.js
  src/components/FilterHeaderButton.js
  src/components/FilterHeaderCategories.js
  src/components/NumberBadge.js
  src/components/__snapshots__/ConnectedFilterHeader.test.js.snap
  src/components/__snapshots__/FilterHeader.test.js.snap
  src/components/__snapshots__/FilterHeaderButton.test.js.snap
  src/components/__snapshots__/FilterHeaderCategories.test.js.snap
  src/components/__snapshots__/NumberBadge.test.js.snap
  src/constants/text.js
  src/screens/CategoriesFilterScreen/__snapshots__/Header.test.js.snap
Labels: ready for review

#245 46 (Part 1) Recurring dates in event details
  src/constants/text.js
  src/data/event.js
  src/data/formatters.js
  src/data/formatters.test.js
  src/screens/EventDetailsScreen/EventOverview.js
  src/screens/EventDetailsScreen/EventOverview.test.js
  src/screens/EventDetailsScreen/RecurrenceDates.js
  src/screens/EventDetailsScreen/RecurrenceDates.test.js
  src/screens/EventDetailsScreen/__snapshots__/EventOverview.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/RecurrenceDates.test.js.snap
Labels: ready for review

#257 100-Correct prices
  scripts/generate-content/generators.js
  src/actions/events.js
  src/components/EventCard.js
  src/components/EventCard.test.js
  src/components/EventList.js
  src/components/EventList.test.js
  src/components/__snapshots__/EventCard.test.js.snap
  src/components/__snapshots__/EventList.test.js.snap
  src/data/event.js
  src/data/formatters.js
  src/data/formatters.test.js
  src/integrations/storage.js
  src/integrations/storage.test.js
  src/screens/EventDetailsScreen/EventDescription.test.js
  src/screens/EventDetailsScreen/EventOverview.js
  src/screens/EventDetailsScreen/EventOverview.test.js
  src/screens/EventDetailsScreen/__snapshots__/EventOverview.test.js.snap
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.test.js
  src/screens/SavedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/SavedEventListScreen/component.test.js
  src/selectors/event.js
Labels: ready for review

#260 Run react-native-git-upgrade
  ios/PrideLondonApp.xcodeproj/xcshareddata/xcschemes/PrideLondonApp.xcscheme
  package.json
  yarn.lock
Labels: ready for review

#265 Parade screen
  assets/images/cabaret.jpg
  assets/images/cabaret@2x.jpg
  assets/images/cabaret@3x.jpg
  assets/images/community.jpg
  assets/images/community@2x.jpg
  assets/images/community@3x.jpg
  assets/images/familyArea.jpg
  assets/images/familyArea@2x.jpg
  assets/images/familyArea@3x.jpg
  assets/images/trafalgarSquare.jpg
  assets/images/trafalgarSquare@2x.jpg
  assets/images/trafalgarSquare@3x.jpg
  assets/images/womensStage2018.jpg
  assets/images/womensStage2018@2x.jpg
  assets/images/womensStage2018@3x.jpg
  src/App.js
  src/components/ImageHeader.js
  src/components/ImageHeader.test.js
  src/components/__snapshots__/ImageHeader.test.js.snap
  src/constants/text.js
  src/screens/DonateScreen/__snapshots__/index.test.js.snap
  src/screens/ParadeInformationScreen/__snapshots__/component.test.js.snap
  src/screens/ParadeInformationScreen/component.js
  src/screens/ParadeInformationScreen/component.test.js
  src/screens/ParadeInformationScreen/index.js
  src/screens/SupportUsScreen/__snapshots__/index.test.js.snap
Labels: ready for review

#232 Favouriting events: Unable to tap favourite on EventCard with VoiceOver enabled
  src/components/EventCard.js
  src/components/EventCard.test.js
  src/components/EventList.js
  src/components/EventList.test.js
  src/components/__snapshots__/EventCard.test.js.snap
  src/components/__snapshots__/EventList.test.js.snap
  src/constants/colors.js
  src/screens/EventDetailsScreen/EventOverview.js
  src/screens/EventDetailsScreen/__snapshots__/EventOverview.test.js.snap
  src/screens/HomeScreen/component.js
Labels: qa approved

#243 156 Header banner
  assets/images/homeSupportUsBgBottomLeft.png
  assets/images/homeSupportUsBgBottomLeft@2x.png
  assets/images/homeSupportUsBgBottomLeft@3x.png
  assets/images/homeSupportUsBgTopRight.png
  assets/images/homeSupportUsBgTopRight@2x.png
  assets/images/homeSupportUsBgTopRight@3x.png
  src/App.js
  src/App.test.js
  src/Navigation.js
  src/Navigation.test.js
  src/__snapshots__/App.test.js.snap
  src/components/ButtonWithShapes.js
  src/components/ButtonWithShapes.test.js
  src/components/FilterHeader.js
  src/components/Header.js
  src/components/Text.js
  src/components/__snapshots__/ButtonWithShapes.test.js.snap
  src/components/__snapshots__/ConnectedFilterHeader.test.js.snap
  src/components/__snapshots__/FilterHeader.test.js.snap
  src/components/__snapshots__/Header.test.js.snap
  src/components/__snapshots__/Text.test.js.snap
  src/constants/text.js
  src/data/get-asset-source.test.js
  src/data/header-banner.js
  src/index.js
  src/screens/CategoriesFilterScreen/component.js
  src/screens/EventsScreen/component.js
  src/screens/FeaturedEventListScreen/component.js
  src/screens/HomeScreen/Header.js
  src/screens/HomeScreen/Header.test.js
  src/screens/HomeScreen/__snapshots__/Header.test.js.snap
  src/screens/HomeScreen/__snapshots__/component.test.js.snap
  src/screens/HomeScreen/__test-data.js
  src/screens/HomeScreen/component.js
  src/screens/HomeScreen/component.test.js
  src/screens/HomeScreen/index.js
  src/screens/SavedEventListScreen/component.js
  src/screens/SupportUsScreen/__snapshots__/index.test.js.snap
  src/screens/SupportUsScreen/index.js
  src/selectors/header-banner.js
  src/selectors/header-banner.test.js
Labels: ready for review

#267 Disable image rendering in markdown
  src/components/Text.js
  src/components/Text.test.js
  src/components/__snapshots__/Text.test.js.snap
Labels: ready for review

#269 Fix parade screen on android
  src/components/ImageHeader.js
Labels: qa approved

#242 Analytics: screen tracking
  android/app/src/main/java/org/prideinlondon/festival/Analytics.java
  android/app/src/main/java/org/prideinlondon/festival/AnalyticsPackage.java
  android/app/src/main/java/org/prideinlondon/festival/MainApplication.java
  ios/PrideLondonApp.xcodeproj/project.pbxproj
  ios/PrideLondonApp/Analytics.h
  ios/PrideLondonApp/Analytics.m
  src/actions/index.js
  src/actions/index.test.js
  src/actions/navigation.js
  src/actions/navigation.test.js
  src/index.js
  src/integrations/analytics.js
  src/integrations/analytics.test.js
Labels: qa approved, ready for review

#256 Fix: Header text 'Filter Events' is not aligned to the center of screen
  src/components/Header.js
  src/components/Header.test.js
  src/components/__snapshots__/Header.test.js.snap
  src/screens/DonateScreen/__snapshots__/index.test.js.snap
  src/screens/DonateScreen/index.js
  src/screens/DonateScreen/index.test.js
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  src/screens/FeaturedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/FeaturedEventListScreen/component.js
  src/screens/FilterModal/Header.js
  src/screens/FilterModal/__snapshots__/Header.test.js.snap
  src/screens/SponsorScreen/__snapshots__/component.test.js.snap
  src/screens/SponsorScreen/component.js
  src/screens/SponsorScreen/component.test.js
Labels: UI, ready for review

#274 Parade view tweaks
  src/constants/text.js
  src/screens/ParadeInformationScreen/__snapshots__/component.test.js.snap
  src/screens/ParadeInformationScreen/component.js
Labels: ready for review

#263 ImageHeader title spacing fix
  src/components/ImageHeader.js
  src/components/__snapshots__/ImageHeader.test.js.snap
  src/screens/HomeScreen/Header.js
  src/screens/HomeScreen/__snapshots__/Header.test.js.snap
Labels: UI, ready for review

#276 Lock app to portrait view
  android/app/src/main/AndroidManifest.xml
  ios/PrideLondonApp/Info.plist
Labels: ready for review

#271 156 Header banner - status bar
  src/App.js
  src/Navigation.js
  src/__snapshots__/App.test.js.snap
  src/components/FilterHeader.js
  src/components/Header.js
  src/components/__snapshots__/ConnectedFilterHeader.test.js.snap
  src/components/__snapshots__/FilterHeader.test.js.snap
  src/screens/DonateScreen/__snapshots__/index.test.js.snap
  src/screens/DonateScreen/index.js
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  src/screens/FilterModal/Header.js
  src/screens/HomeScreen/__snapshots__/component.test.js.snap
  src/screens/HomeScreen/component.js
  src/screens/SponsorScreen/__snapshots__/component.test.js.snap
  src/screens/SponsorScreen/component.js
Labels: qa approved, ready for review

#284 Adding Bugsnag thank you
  README.md
Labels: ready for review

#282 Fix heart flicker on iOS
  src/components/EventCard.js
  src/components/SaveEventButton.js
  src/components/SaveEventButton.test.js
  src/components/Text.test.js
  src/components/__snapshots__/SaveEventButton.test.js.snap
Labels: qa approved, ready for review

#283 BUG - Fix filter for event times
  src/selectors/basic-event-filters.js
  src/selectors/basic-event-filters.test.js
Labels: ready for review

#277 Adding label to category filter button
  src/components/FilterHeaderCategories.js
  src/components/FilterHeaderCategories.test.js
  src/components/__snapshots__/FilterHeaderCategories.test.js.snap
  src/constants/text.js
Labels: ready for review

#294 Ignore platform folders in flow config
  .flowconfig
Labels: ready for review

#296 Remove isFree and timeOfDay from event data
  src/screens/EventDetailsScreen/EventDescription.test.js
  src/screens/EventDetailsScreen/EventOverview.test.js
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.test.js
  src/screens/SavedEventListScreen/__snapshots__/component.test.js.snap
  src/screens/SavedEventListScreen/component.test.js
Labels: ready for review

#246 46 (Part 2) - Recurring events in event list
  README.md
  src/data/formatters.js
  src/data/formatters.test.js
  src/reducers/events.js
  src/reducers/events.test.js
  src/screens/EventDetailsScreen/RecurrenceDates.js
  src/selectors/events.js
  src/selectors/events.test.js
Labels: ready for review

#299 Increase size of Heart icon on Android
  src/screens/SavedEventListScreen/NoSavedEvents.js
  src/screens/SavedEventListScreen/__snapshots__/NoSavedEvents.test.js.snap
Labels: ready for review

#298 Fix: Too much space below status bar
  src/components/Header.js
  src/components/__snapshots__/Header.test.js.snap
Labels: ready for review

#301 add core-js to polyfill padStart on Android
  package.json
  src/index.js
  yarn.lock
Labels: ready for review

#297 Correct event types for optional fields
  src/data/event.js
  src/screens/EventDetailsScreen/__snapshots__/component.test.js.snap
  src/screens/EventDetailsScreen/component.js
  src/screens/EventDetailsScreen/component.test.js
  src/selectors/events.js
Labels: ready for review

#266 241 multiple nav stack
  e2e/firstTest.spec.js
  package.json
  src/Navigation.js
  src/Navigation.test.js
  src/components/NavigationTabBar.js
  src/components/NavigationTabBar.test.js
  src/components/__snapshots__/NavigationTabBar.test.js.snap
  src/screens/CategoriesFilterScreen/component.js
  src/screens/DonateScreen/index.js
  src/screens/EventDetailsScreen/component.js
  src/screens/FeaturedEventListScreen/component.js
  src/screens/SponsorScreen/component.js
  yarn.lock
Labels: ready for review

#309 305: Filter recurring events happening on same day
  src/selectors/events.js
  src/selectors/events.test.js
Labels: qa approved

#317 Fix analytics screen event tracking
  src/App.js
  src/App.test.js
  src/__snapshots__/App.test.js.snap
Labels: ready for review

#316 Fix filter by date
  package.json
  src/data/formatters.js
  src/selectors/events.js
  src/selectors/events.test.js
  yarn.lock
Labels: qa approved, ready for review

#303 120 accessibility labels
  src/components/CategoriesPills.js
  src/components/FilterHeaderCategories.js
  src/components/FilterHeaderCategories.test.js
  src/components/__snapshots__/CategoriesPills.test.js.snap
  src/components/__snapshots__/FilterHeaderCategories.test.js.snap
  src/constants/text.js
Labels: qa approved, ready for review

#314 Filters accessibility labels
  src/components/CheckBox.js
  src/components/__snapshots__/CheckBox.test.js.snap
  src/data/accessibility.android.js
  src/data/accessibility.ios.js
  src/data/accessibility.test.js
  src/screens/CategoriesFilterScreen/ListItem.js
  src/screens/CategoriesFilterScreen/__snapshots__/ListItem.test.js.snap
Labels: qa approved, ready for review

#292 Attempt to provide better accessibility for TextInput
  src/components/Touchable.android.js
  src/screens/DonateScreen/NumberTextField.js
  src/screens/DonateScreen/NumberTextField.test.js
  src/screens/DonateScreen/__snapshots__/NumberTextField.test.js.snap
  src/screens/DonateScreen/__snapshots__/accessibilityLabel.android.test.js.snap
  src/screens/DonateScreen/__snapshots__/accessibilityLabel.ios.test.js.snap
  src/screens/DonateScreen/__snapshots__/index.test.js.snap
  src/screens/DonateScreen/accessibilityLabel.android.js
  src/screens/DonateScreen/accessibilityLabel.android.test.js
  src/screens/DonateScreen/accessibilityLabel.ios.js
  src/screens/DonateScreen/accessibilityLabel.ios.test.js
  src/screens/DonateScreen/index.js
Labels: qa approved, ready for review

#333 Filtering navigation UX
  src/Navigation.js
  src/components/CategoriesPills.js
  src/components/CategoriesPills.test.js
  src/components/__snapshots__/CategoriesPills.test.js.snap
  src/constants/text.js
  src/screens/CategoriesFilterScreen/Header.js
  src/screens/CategoriesFilterScreen/Header.test.js
  src/screens/CategoriesFilterScreen/__snapshots__/Header.test.js.snap
  src/screens/CategoriesFilterScreen/__snapshots__/component.test.js.snap
  src/screens/CategoriesFilterScreen/component.js
  src/screens/CategoriesFilterScreen/component.test.js
  src/screens/CategoriesFilterScreen/index.test.js
  src/screens/FilterScreen/FilterList.js
  src/screens/FilterScreen/FilterList.test.js
  src/screens/FilterScreen/FilterSectionList.js
  src/screens/FilterScreen/FilterSectionList.test.js
  src/screens/FilterScreen/Header.js
  src/screens/FilterScreen/Header.test.js
  src/screens/FilterScreen/__snapshots__/FilterList.test.js.snap
  src/screens/FilterScreen/__snapshots__/FilterSectionList.test.js.snap
  src/screens/FilterScreen/__snapshots__/Header.test.js.snap
  src/screens/FilterScreen/__snapshots__/component.test.js.snap
  src/screens/FilterScreen/component.js
  src/screens/FilterScreen/component.test.js
  src/screens/FilterScreen/index.js
Labels: ready for review

#320 refresh events on foregrounding
  src/actions/events.js
  src/actions/events.test.js
  src/index.js
  src/integrations/cms.js
  src/integrations/cms.test.js
Labels: ready for review

#336 Fix filter back gesture
  src/actions/event-filters.js
  src/components/EventList.js
  src/components/__snapshots__/EventList.test.js.snap
  src/reducers/__snapshots__/route.test.js.snap
  src/reducers/event-filters.js
  src/reducers/event-filters.test.js
  src/reducers/index.js
  src/reducers/route.js
  src/reducers/route.test.js
  src/screens/CategoriesFilterScreen/component.js
  src/screens/CategoriesFilterScreen/component.test.js
  src/screens/CategoriesFilterScreen/index.js
  src/screens/CategoriesFilterScreen/index.test.js
  src/screens/EventsScreen/component.js
  src/screens/EventsScreen/index.js
  src/screens/FilterScreen/component.js
  src/screens/FilterScreen/component.test.js
  src/screens/FilterScreen/index.js
  src/selectors/event-filters.test.js
Labels: ready for review

#328 Hide past events
  package.json
  src/Navigation.js
  src/Navigation.test.js
  src/components/ConnectedDateFilterDialog.test.js
  src/constants/routes.js
  src/data/event-filters.js
  src/data/event.js
  src/lib/date.js
  src/reducers/__snapshots__/event-filters.test.js.snap
  src/reducers/event-filters.js
  src/reducers/event-filters.test.js
  src/reducers/index.js
  src/screens/CategoriesFilterScreen/index.test.js
  src/selectors/event-filters.test.js
  src/selectors/events.js
  src/selectors/events.test.js
  yarn.lock
Labels: ready for review

#338 Sends Slack message when release build fails on either platform
  .circleci/config.yml
  android/fastlane/Fastfile
  ios/fastlane/Fastfile
Labels: ready for review

#342 Fade previous days in calendar
  src/components/DateRangePickerDay.js
  src/components/DateRangePickerDay.test.js
  src/components/__snapshots__/DateRangePickerDay.test.js.snap
  src/lib/date.js
  src/lib/dates.test.js
Labels: qa approved

#344 Refactor events to data
  src/actions/data.js
  src/actions/data.test.js
  src/components/ConnectedDateFilterDialog.test.js
  src/index.js
  src/reducers/__snapshots__/data.test.js.snap
  src/reducers/data.js
  src/reducers/data.test.js
  src/reducers/index.js
  src/screens/CategoriesFilterScreen/index.test.js
  src/screens/EventsScreen/index.js
  src/screens/SavedEventListScreen/index.js
  src/selectors/event-filters.test.js
  src/selectors/events.js
  src/selectors/events.test.js
  src/selectors/header-banner.js
  src/selectors/header-banner.test.js
  src/selectors/sponsors.js
  src/selectors/sponsors.test.js
Labels: ready for review
